raulvillares/3sacrowd

js/levels.js
js/properties.js

Though there is now an issue with the CSS which causes the background to not expand to cover on higher levels. There is also an issue where each level is ordered by 5s like the first set of levels but beyond level 7 which was there before I touched the project, this is no longer how it should be.

Added levels 8-19 from provided source

---

styles.css

In order for the background to be more responsive, I have changed the background size to cover and position to cover, cover.

#13 Updated background properties

---

index.html
styles.css

Hi! I'm a first time open source contributor. I looked over this awesome game and picked out a couple things I think can visually improve the landing page. I'll look through the issues you have and do my best to  help you out.
For this PR, I noticed the bottom description text was going over two different colors and I thought it might be easier to read if it was moved down into the green background.
Also, the "Start" image link is making the whole div a clickable link. I modified the CSS to just wrap the image itself. I'm not sure if you meant for this to be the functionality so let me know.

[3sacrowd] spacing

---

js/square.js

In reference to issue #2, better styling on pinned

updated pinned border styling

---

gameplay.html

I think this might be what you're asking for.  Sorry for taking so long. I thought the last pull request was correct.

Add title and favicon

---

README.md

Most of this is just to improve the grammar/spelling, while some I feel are improvements that make the description just sound a bit better :-)

Updated README for grammar, typos, and clarity.

---

js/board.js
js/buttons.js

Hi, 
Thanks for giving us first-timers something to work on... I just dived right in and done some of the changes needed in codacy....I hope they are satisfactory..
Thanks

Codacy issues #5

---

README.md
gameplay.html
index.html
styles.css

Hi! Came across your project on up-for-grabs and wanted to contribute :) hope that's okay! 
The text below is a summary of what was changed in this PR. 
Change target='blank' to target='_blank'
Add noopener noreferrer to close target='_blank' vulnerability
Add lang attribute to html tags for better accessibility
Use 'bold' CSS class instead of strong tags for making text bold for better accessibility
Fix typos on index.html page
Update grammar structure in README

Miscellaneous Markup and CSS updates

---

.gitignore
js/board.js
styles.css

Added labels to the medals feature so the user knows what achievements were reached. 
I also abstracted the logic of setting the medal on/off state to a separate function to avoid having to update logic in multiple places.

Medal labels

---

js/info.js

Added Enhancements for 
-- Displaying the Max time.
-- Displaying the max moves.
As per the comment https://github.com/raulvillares/3sacrowd/issues/24#issuecomment-322903340

Added Code to show Max Movements and Max Time String

---

test/infoTest.js
test/levelsTest.js

Modified the two test files to remove Codacy errors. 
If you set Codacy to ignore the require.js file that should give an A grade.
Have tested and game runs in it's current state. 
Visit leonsinclair.github.io/3sacrowd to confirm.

Fixing minor Codacy issues.

---

index.html
package-lock.json

adding "alt" attributes of images in index.html, also the indentation was edited, to improve the quality of the code.

Adding img alt attributes

---

index.html
js/board.js

When the user hovers over the squares **which can be changed** upon mouse click in the present state (eg.If the pin button is on so only pinnable squares will interact"), then the square increases in size.
This improves the feel of the game.

Made Start buttons and squares interactive with mouse hover

---

index.html
js/board.js

Reverts raulvillares/3sacrowd#37
Uncaught SyntaxError: Unexpected token {
levelLoader.js:39 Uncaught TypeError: Cannot read property 'createEmptyBoard' of undefined
at generateBoard (levelLoader.js:39)
at loadFunction (levelLoader.js:56)
at Object.loadLevel (levelLoader.js:66)
at gameplay.js:2
at Object.execCb (require.js:5)
at b.check (require.js:5)
at b.<anonymous> (require.js:5)
at require.js:5
at require.js:5
at each (require.js:5)

Revert "Made Start buttons and squares interactive with mouse hover"

---

.eslintignore
.eslintrc.yml
js/info.js
js/sound.js

This fixes all the problems reported by Codacy.
Fixes #5

Fix Codacy Issues

---

index.html
js/board.js

The previous effect of enlargened tiles upon mouseover has been restored. Syntax errors have been fixed.

Mouseover effect restoration

---

README.md
package-lock.json
test/levelsTest.js

Hi! I'm a beginning programmer at a bootcamp and was happy to find a beginner-friendly repo!
I took a swing at the level testing. They just check that all of the levels are well-formed.
Thanks!
Ian

Fixed README file name, created level tests

---

package-lock.json
test/levelsTest.js

This commit does the following:
- Refactored initialSquaresCheck, putting loops etc into a separate function to clean up the testing code.
- Added necessary functions that will evaluate/play through the board and return the number of possible solutions, then check that the number of solutions for each board is 1.

Added test to check solution is possible and unique

---

js/board.js

Name for badges are now not hidden when the board is completed.

Resolved issue1, name for badges now not hidden when completed

---

gameplay.html
index.html
js/info.js
js/levelLoader.js
styles.css

… and adding minor styles for gameplay making it look more like a SPA
Removed Comments and no more merge conflicts

css instead of event listener.

---

animation.css
gameplay.html
js/board.js
js/info.js
js/levelLoader.js
js/square.js
styles.css

Making the minor changes you have requested.

Animation issue changes

---

animation.css
gameplay.html
index.html
js/board.js
js/info.js
js/levelLoader.js
js/square.js
styles.css

hacktoberfest-Pull-Request Making it so the box shakes if its empty and cant be changed

Animation issue

---

README.md

Also replaced npm install babel-preset-es2015 with babel/preset-env, as the former is deprecated.

Updated README.md to show more instructions

---

test/infoTest.js

Hi Raul Villares,
I'd like to contribute a simple unit test to infoTest.js where I test that the movement counter gets incremented from 0 to 1.
Kind Regards,
Gary Khong

add movement and movement total test

---

gameplay.html

… so that it sends to the main page index.jtml, hope you 💯 like it

made the game logo on the game.html clickable  thought it would improve the user experience 

---

js/gameLogic.js
package-lock.json
package.json
test/allTests.js
test/test.js

This Pull Request introduces automated tests for the solution validation logic in the **3sacrowd** game.
**Changes made:**
- Added `Test.js` with tests for the `isSolutionCorrect` function.
- Tested various cases including:
- A correct solution.
- Incorrect solutions with wrong values and incorrect lengths.
- An empty solution.
**Purpose:**
- To ensure the correctness of the solution validation logic.
- To prevent future changes from breaking the validation functionality.
- To enhance code reliability by adding automated validation tests.
**Testing:**
- Run `npm install` to ensure dependencies are up-to-date.
- Execute tests using `npm test`.
**Notes:**
- Update import paths in the test file according to project structure.

Add tests for solution validation logic
